### ISSUE TITLE
[Feature] Consider introduce `databend` chart

### ISSUE THREAD

**Issue by junnplus** [datafuselabs/helm-charts#4]
We can consider introduce another chart -- `databend`, which can contain two components at the same time, users can create `databend-meta` and `databend-query` with one yaml file.

```yaml
meta:
  enabled: true
query:
  enabled: true
  config:
    meta:
      embedded:
        enabled: false
      address: xxx:9191
```
Or introduce `databend-meta` dependency in `databend-query`:
```yaml
meta:
  enabled: true
config:
  meta:
    embedded:
      enabled: false
    address: xxx:9191
```

_Originally posted by @Junnplus in https://github.com/datafuselabs/helm-charts/issues/1#issuecomment-1091781114_
